### ISSUE TITLE
can't deploy

### ISSUE THREAD

**Issue by grommitz** [payara/Payara-Examples#15]
I can't deploy either the sender or receiver:
`
[2015-09-25T00:02:17.116+0100] [Payara 4.1] [SEVERE] [] [javax.enterprise.web] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1443135737116] [levelValue: 1000] [[
  WebModule[/event-receiver-1.0-SNAPSHOT]StandardWrapper.Throwable
org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke void fish.payara.micro.cdi.ClusteredCDIEventBus.postConstruct() on fish.payara.micro.cdi.ClusteredCDIEventBus@8f589d7
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:100)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:81)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:126)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:171)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:141)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
	at fish.payara.micro.cdi.ClusteredCDIEventBus$Proxy$_$$_WeldClientProxy.initialize(Unknown Source)
	at fish.payara.examples.payaramicro.event.receiver.EventsServlet.init(EventsServlet.java:50)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1583)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1382)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5732)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5977)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:691)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1041)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:1024)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2286)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1932)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:139)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:500)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
	at fish.payara.micro.PayaraMicro.deployAll(PayaraMicro.java:922)
	at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:708)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:105)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:98)
	... 47 more
Caused by: java.lang.NullPointerException
	at fish.payara.micro.cdi.ClusteredCDIEventBus.postConstruct(ClusteredCDIEventBus.java:83)
	... 52 more
`

**Comment by smillidge** [comment]
Hi is this running the example from Maven?

**Comment by grommitz** [comment]
no this was from the command line with --deploy argument. I had some other issue running the deployer app.

**Comment by smillidge** [comment]
Dumb questions are you using Payara Micro 4.1.153?

**Comment by smillidge** [comment]
Actually this is a known issue which has been fixed https://github.com/payara/Payara/commit/1cc8043d58746e6567a727cd6040814974dfc1bb.

Try using the latest pre-release Payara Micro jar from https://s3-eu-west-1.amazonaws.com/payara.co/payara-micro-prerelease.jar

**Comment by grommitz** [comment]
Thanks Steve, it works with the prerelease version.
